### ISSUE TITLE
app.js is missing

### ISSUE THREAD

**Issue by malpaso** [miguelcobain/hapi-boilerplate#2]
The app.js file is missing or is this supposed to be added?

**Comment by miguelcobain** [comment]
I just fixed the main entry in package.json

Everything seems to be working fine.
Please report if you find any issues.

**Comment by miguelcobain** [comment]
The default value for the start script is `server.js`: https://docs.npmjs.com/misc/scripts#default-values

**Comment by IndigoBee** [comment]
You forgot to change it in the readme ;) @miguelcobain
