### ISSUE TITLE
Any plans to update this?

### ISSUE THREAD

**Issue by alexdrans** [miguelcobain/hapi-boilerplate#3]

**Comment by miguelcobain** [comment]
No plans currently. But I think it would just need a package.json version bumps and some ES6 goodness.
I would accept such a PR.

**Comment by duycuong87vn** [comment]
Very useful for me
Please update this project/boilerplate if you can.
THanks

**Comment by alexdrans** [comment]
@duycuong87vn If you're learning Hapi, check out @dwyl 's repos! (Check them out anyway, they're awesome)

**Comment by mstocchi** [comment]
some minor updates on recent hapi.js on pull request
